### ISSUE TITLE
Get audio data from DLNA device

### ISSUE THREAD

**Issue by feliwir** [succlz123/DLNA-Dart#1]
Hello @succlz123 ,
i just found this cool project because i wanted to create an audio player with flutter. However i'm not really sure where to start, what functionality is missing. If you could give me a headsup what is required, i'd also happily contribute.
Thanks

**Comment by succlz123** [comment]
I don't understand what you're trying to do, I'm guessing you want to make a flutter version of the audio player. 
But this DLNA library is just a video casting tool and doesn't have any audio features.

**Comment by feliwir** [comment]
Yeah i didn't know for example that it doesn't have any audio features :)

**Comment by succlz123** [comment]
First I'd like to say that I'm not actually familiar with flutter.

Then, I saw a C# version audio player library in your Github,  so I guess you want to use the IOS or Android NATIVE API to play the audio.
I think you may need to create a flutter plugin to call the different platform API.
For example, using OpenES SE on Android requires you to write both C++ and Java code, then write the flutter plugin to call it.

(Perhaps flutter already provides a well-packaged audio API.) 😃

**Comment by feliwir** [comment]
@succlz123 i am not really familar with DLNA to be honest :) Here is what i want to do:
I have audio files on a network storage / DLNA server, and thought i could access/stream the files with this library. I don't want to play the files with your library, but instead just access / read them. I already know how to play the audio afterwards.
Thanks for your help in advance
