### ISSUE TITLE
ios devices joinMulticast throw error

### ISSUE THREAD

**Issue by a582468113** [succlz123/DLNA-Dart#2]
Now has error when i search on ios devices. It works as expected on Android.

OS Error: Can't assign requested address, errno = 49
flutter: #0      _NativeSocket.nativeJoinMulticast (dart:io-patch/socket_patch.dart:1379:56)
#1      _NativeSocket.joinMulticast (dart:io-patch/socket_patch.dart:1331:5)
#2      _RawDatagramSocket.joinMulticast (dart:io-patch/socket_patch.dart:2127:13)
#3      SSDPController.start (package:dlna/src/ssdp/ssdp_controller.dart:89:17)
<asynchronous suspension>
#4      SSDPController.startSearch (package:dlna/src/ssdp/ssdp_controller.dart:143:13)
#5      DLNAManager._search (package:dlna/src/dlna_manager.dart:82:27)
#6      DLNAManager.startSearch (package:dlna/src/dlna_manager.dart:69:7)

**Comment by succlz123** [comment]
1. Don't run it in the simulator.
2. I don't have any IOS device, so ... (If there is an issue on the real machine, wait until I borrow an IOS phone next time) 😢

**Comment by a582468113** [comment]
@succlz123 
This is dart's bug, i closed the issues. 
I run it on the real ios device, and i found another bugs, i fork my repository and fixed.
How can I communicate with you
