### ISSUE TITLE
Do not work on iOS

### ISSUE THREAD

**Issue by waymon1023** [succlz123/DLNA-Dart#6]
Dear Author，I have a question。
Why can't I find a device when I run on IOS? It's OK on Android

**Comment by fengwensheng** [comment]
> Dear Author，I have a question。
> Why can't I find a device when I run on IOS? It's OK on Android
I'm doing DLNA cast for a video application too. Have you ever solved this problem? There's few solution(package/plugin) for flutter/dart now.

**Comment by fengwensheng** [comment]
@waymon1023 
I'm doing DLNA cast for a video application too. Have you ever solved this problem? There's few solution(package/plugin) for flutter/dart now.

**Comment by waymon1023** [comment]
安卓这边没问题，iOS没解决，还是调用的原生，用的MRDLNA，flutter就等这个大神以后更新吧

**Comment by fengwensheng** [comment]
啊这 用中文早说啊 我这谷歌翻译了老半天了 我这边也是 android 没问题 ios报错了

**Comment by fengwensheng** [comment]
啊这 用中文早说啊 我这谷歌翻译了老半天了 我这边也是 android 没问题 ios报错了 @waymon1023

**Comment by waymon1023** [comment]
我这垃圾百度翻译呢还，洋文不得给外国友人看看吗XD，

**Comment by fengwensheng** [comment]
好吧 这个好像是 dart sdk 的问题 @waymon1023

**Comment by succlz123** [comment]
哈哈 手头没 iOS 手机所以其实没测过, 模拟器又不支持多播. @waymon1023 @fengwensheng  好久前写的, 现在手头也没 DLNA 设备, 有空 有空看下
